### ISSUE TITLE
Windows系のアーカイブを作ることはできなくなったのでしょうか？

### ISSUE THREAD

**Issue by mado-m** [sacloud/packer-plugin-sakuracloud#143]
下記などを参考にWindows Serverのアーカイブを作成したいと考えています。
https://knowledge.sakura.ad.jp/6790/

しかし、下記を見るとos_typeにwindows系の値が見当たりません。
https://github.com/sacloud/packer-plugin-sakuracloud#%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E4%B8%80%E8%A6%A7

例えば下記の例だとos_typeが `windows2016` と書かれていてwindows系も使えそうな感じはします。
https://github.com/sacloud/packer-plugin-sakuracloud/blob/master/examples/windows2016/template.json

しかし、実際にos_type `windows2016` と指定してビルドすると下記のようにinvalidエラーが発生してしまいます。

```
$ packer build ./
Error: 1 error(s) occurred:

* os_type is invalid
```

Windows系のアーカイブを作ることは現在可能でしょうか？

**Comment by yamamoto-febc** [comment]
> Windows系のアーカイブを作ることは現在可能でしょうか？

可能です。
`os_type`に`custom`を指定した上で`source_archive`または`source_disk`を指定することで可能となります。
参考: [オプション一覧](https://github.com/sacloud/packer-plugin-sakuracloud/blob/457933f6bbb2455706f65f992a2415c194500c61/README.md#オプション一覧)

> 例えば下記の例だとos_typeが windows2016 と書かれていてwindows系も使えそうな感じはします。
> https://github.com/sacloud/packer-plugin-sakuracloud/blob/master/examples/windows2016/template.json

古いドキュメントが残ってしまっている状態です。
Issueをあげておきました -> #144

**Comment by yamamoto-febc** [comment]
回答済みのためクローズします。追加で質問などありましたら再オープンしてください。
